name: Deploy Orchestrator Relay (Azure Functions)

on:
  workflow_dispatch:
  push:
    paths:
      - orchestrator-relay/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_PATH: orchestrator-relay
      PUBLISH_DIR: publish
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet restore $PROJECT_PATH
      - run: dotnet publish $PROJECT_PATH -c Release -o $PUBLISH_DIR
      - name: Deploy to Azure Functions
        uses: azure/webapps-deploy@v3
        with:
          publish-profile: ${{ secrets.AZUREAPPSVC_PUBLISH_PROFILE }}
          package: ${{ env.PUBLISH_DIR }}
