name: Deploy Orchestrator Relay (Azure Functions)

on:
  workflow_dispatch:
  push:
    paths:
      - orchestrator-relay/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_PATH: orchestrator-relay
      PUBLISH_DIR: publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore $PROJECT_PATH

      - name: Publish
        run: dotnet publish $PROJECT_PATH -c Release -o $PUBLISH_DIR

      # Deploy oficial para Azure Functions con Publish Profile
      - name: Deploy to Azure Functions
        uses: azure/functions-action@v1
        with:
          publish-profile: ${{ secrets.AZUREAPPSVC_PUBLISH_PROFILE }}
          app-name: rimp-orch-relay           # EXACTO como en Azure
          package: ${{ env.PUBLISH_DIR }}
